spring.application.name=TrueHire
server.port=8080

# H2 in-memory
spring.datasource.url=jdbc:h2:mem:truehire
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Консоль H2 доступна на /h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
