CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE job_vacancy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(3000),
    work_conditions VARCHAR(2000),
    candidate_requirements VARCHAR(2000),
    employer_id BIGINT NOT NULL
);

CREATE TABLE job_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id BIGINT NOT NULL,
    candidate_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE interview_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE,
    ai_language_score VARCHAR(255),
    ai_soft_skills_comment VARCHAR(2000),
    interview_record_url VARCHAR(255),
    is_passed BOOLEAN NOT NULL
);

CREATE TABLE visa_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    file_url VARCHAR(255),
    status VARCHAR(255) NOT NULL
);

CREATE INDEX idx_job_application_candidate ON job_application (candidate_id);
CREATE INDEX idx_job_application_vacancy ON job_application (vacancy_id);
CREATE INDEX idx_visa_document_application ON visa_document (application_id);
