ALTER TABLE job_vacancy
ADD COLUMN interview_template_id VARCHAR(100) NOT NULL DEFAULT 'hrme-warsaw';

ALTER TABLE job_application ADD COLUMN external_interview_id BIGINT;
ALTER TABLE job_application ADD COLUMN external_interview_token VARCHAR(255);
ALTER TABLE job_application ADD COLUMN external_interview_url VARCHAR(500);
ALTER TABLE job_application ADD COLUMN interview_started_at TIMESTAMP;
ALTER TABLE job_application ADD COLUMN interview_completed_at TIMESTAMP;

CREATE UNIQUE INDEX idx_job_application_external_interview
ON job_application (external_interview_id);

CREATE TABLE site_visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key VARCHAR(64) NOT NULL,
    path VARCHAR(255) NOT NULL,
    visited_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_site_visit_visited_at ON site_visit (visited_at);
CREATE INDEX idx_site_visit_session_visited ON site_visit (session_key, visited_at);
CREATE INDEX idx_site_visit_path ON site_visit (path);
